# -*- coding: utf-8 -*-
"""ПЗ 2 Манакова

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkWZDZdhcE0xxSLvcLwIUXA4xgRdij7h
"""

number = input("Введите двухзначное число: ")

while True:
    try:
        # Проверка на целое число
        number = int(number)

        # Проверка на двузначное число
        if number < 10 or number > 99:
            print("Число должно быть двузначным.")
            number = input("Попробуйте снова: ")
            continue

        # Поиск десятков и единиц
        des = number // 10
        ost = number % 10

        # Вывод результата
        print("Десятки:", des)
        print("Единицы:", ost)
        break

    except ValueError:
        print("Неправильно ввели число! Введите целое число.")
        number = input("Попробуйте снова: ")